name: Destroy AWS Infrastructure

on:
  workflow_dispatch:  # 手动触发

env:
  AWS_REGION: us-east-1
  TF_WORKING_DIR: ./terraform

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -upgrade

      - name: Confirm Destroy
        id: confirm
        run: |
          echo "🚨 WARNING: This will DESTROY all AWS resources including:"
          echo "• ECS Cluster & Service"
          echo "• RDS Database (ALL DATA WILL BE LOST)"
          echo "• ALB, VPC, NAT, Subnets, and ECR"
          echo ""
          echo "To continue, set DESTROY=YES as an input in workflow_dispatch."

      - name: Terraform Destroy
        if: ${{ github.event.inputs.DESTROY == 'YES' }}
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -auto-approve
